### ISSUE TITLE
XFCE4-Terminal as dependancy

### ISSUE THREAD

**Issue by sk9la** [martin-olivier/airgorah#53]
Hi,

When I installed Airgorah using the following command: `cargo install airgorah` The installation was successful, but impossible to Lunch:
`[2023-11-20T15:51:58Z ERROR airgorah::frontend::widgets::dialog] missing required dependency: "xfce4-terminal"`

I don't know why it asks for Xfce Terminal since I'm using Kali Linux on Gnome ?

Any ideas ?

**Comment by martin-olivier** [comment]
Hello @sk9la,

I'm using `xfce4-terminal` to spawn the handshake decryption window, that runs `aircrack-ng`.
I'm using this instead on `gnome-terminal` because there is an option in `xfce4-terminal` to launch only one command and then not be able to reuse the shell afterward.

If you download the debian file on the [release page](https://github.com/martin-olivier/airgorah/releases/tag/latest), and then install it using the following command, do you have some errors ? If so, can you share me the logs ?

```
sudo apt update && sudo apt install <path_to_deb_file>
```

BR

**Comment by martin-olivier** [comment]
It's strange because the debian package should automatically install `xfce4-terminal`.

Does it work if you install it manually ?
```
sudo apt install xfce4-terminal
```

> Is there a way to configure the choice of terminal ? Because I can't even launch it ?

No, for the moment, Airgorah uses only `xfce4-terminal`, but I will add multi term support in a future release

**Comment by martin-olivier** [comment]
@sk9la

I have open a separate issue to add multi-term support.
You can still try airgorah without installing XFCE by doing so:

1. Clone the project
2. Go to `src/backend/app.rs`
3. Comment the `line 31`:
```rust
[...]
    check_required_dependencies(&[
        "sh",
        "systemctl",
        "ip",
        "iw",
        "awk",
        "airmon-ng",
        "airodump-ng",
        "aireplay-ng",
        "aircrack-ng",
        //"xfce4-terminal",
        "mergecap",
        "macchanger",
    ])
}
[...]
```
4. Install the project
```sh
cargo install --path .
```
5. Run the project
```
sudo airgorah
```

Everything will work fine except the start of handshake decryption with `airgorah`
