### ISSUE TITLE
Bug: it's freeze sometimes with version 0.7.0

### ISSUE THREAD

**Issue by pavnguyen** [martin-olivier/airgorah#62]
Hello, 

I have a weird issue, sometime it's freeze my computer when using version 0.7.0.

So I tried to run the command in terminal like airodump. aireplay, mdk4, etc.... it's still working no problem. So I guess it's not related to my computer or my system linux.

@martin-olivier Please take a look about the handling errors

**Comment by pavnguyen** [comment]
@martin-olivier 

I think it's about the pacquet speed, we can adjust slow down the speed pacquet/s and the issue will be dissapears.

**Comment by martin-olivier** [comment]
Hello @pavnguyen,

This freezing issue is probably due to the new feature `vendors` (if this lag is new on the `v0.7.0`), because it is actually done in the frontend, and It can take a lot of time to find the vendor from the MAC address in a big `HashMap`.

I will fix that and the other issues you opened from the 10th of january.

**Comment by martin-olivier** [comment]
Hello @pavnguyen,

Sorry for the long delay. I have fixed the freezing issues on the `dev` branch, by moving the vendors finder on a separate thread on the backend.

Can you tell me if it fixed the issue you reported ?
